### ISSUE TITLE
Lamps Render Incorrectly Next to Other Blocks

### ISSUE THREAD

**Issue by WenXin20** [SaymN/VanillaThings#1]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Vanilla Things v0.4.6`

- When a lamp is placed next to another block, such as carpet, its side renders invisible.
- Double Glass slabs were also rendering opaque instead of clear, but that may be because of the Double Slabs mod.

![2020-02-16_19 18 43](https://user-images.githubusercontent.com/12000593/74617677-00918300-50f4-11ea-9423-9817dc75aeee.png)

**Comment by SaymN** [comment]
Thanks for your info, i will fix in next time :)

**Comment by WenXin20** [comment]
Thanks! Also noticed that the Spruce Lamps and others all look like the oak lamps.

**Comment by SaymN** [comment]
Yea its, the same render type for all type of lamps

**Comment by SaymN** [comment]
If you have time... Can you check if the hanging lamp has the same problem if there's a carpet or something next to it?

**Comment by WenXin20** [comment]
Yeah, it does. It's in the image on the left actually. :)-----------------------Sincerely, David NewvilleOn Feb 17, 2020 1:14 AM, SaymN <notifications@github.com> wrote:If you have time... Can you check if the hanging lamp has the same problem if there's a carpet or something next to it?

**Comment by SaymN** [comment]
I mean the hanging lamp, not the wall lamp^^

**Comment by WenXin20** [comment]
Oh, oops! I'll have to check tomorrow.

**Comment by SaymN** [comment]
I will look tonight ;)

**Comment by WenXin20** [comment]
I don't see any hanging lanterns? 
And I'm not sure if I said this right, but the spruce planks lantern looks like its made of oak planks, same for the other plank lanterns.

**Comment by SaymN** [comment]
The "Culling" argument remove din the next update.

**Comment by SaymN** [comment]
@WenXin20 
Place a normal lamp on the ceiling ;)

**Comment by WenXin20** [comment]
Oh, thanks!
