### ISSUE TITLE
No Recipes for Most Items

### ISSUE THREAD

**Issue by jon-bartus** [SaymN/VanillaThings#10]
So, I installed your mod on my 1.15.2 installation and there appear to be no valid recipes for the following:

- All Stairs
- All Slabs
- All Vertical Slabs
- All Walls
- The Lamp Table

I tested the mod under the following conditions:

- Custom 1.15.2 Modpack running Forge 31.1.18 with Vanilla Things 0.5.7 and 31 other mods.
- Custom 1.15.2 Modpack running Forge 31.1.27 with Vanilla Things 0.5.7 and 31 other mods.
- Custom 1.15.2 Modpack running Forge 31.1.27 with Vanilla Things 0.5.7 and Just Enough Items 6.0.0.2

According to JEI, there are no recipes available for any of these items in any of these configurations.

**Comment by SaymN** [comment]
All of this items can only be craftet in the stonecutter. (Look in the Vanills Things changelogs)
And JEI does not support the stonecutter recipes.

**Comment by jon-bartus** [comment]
I'm on my way to bed (need to write up another issue first) but your reply here makes #11 even more pertinent.

I, in fact, checked https://github.com/SaymN/VanillaThings/blob/1.15.2/changelog.txt which is utterly useless as, again, it doesn't actually belong to your project. So, that leaves me with the Curse changelogs which are just about the least user-friendly place to put vital information such as this because the user has to navigate manually to each version of the file in order to see the log. Further complicating this matter, there's no way to view the change log for each version of the file from within the Curse/Twitch launcher.

I will check this out in the morning and, if the recipes work the way you say they should, I'll close this issue. That said, expect to see an additional suggestion issue popping up if this is, in fact, accurate.

**Comment by jon-bartus** [comment]
Decided to go ahead and check this out and your information here is accurate, though I will naturally be posting the suggestion as promised.

**Comment by SaymN** [comment]
I know what you mean with the changlogs.
So i will add a log over all versions.
