### ISSUE TITLE
Readme File is Completely Useless

### ISSUE THREAD

**Issue by jon-bartus** [SaymN/VanillaThings#11]
From what I can tell, you've just uploaded the ForgeGradle Readme.txt which is absolutely useless to someone trying to use your mod. Overall, there's no documentation whatsoever with regards to this mod, which means my other issue I've posted may not be accurate, but without any indication of what I'm supposed to be doing, I can only assume that the mod is broken.

Please create a Readme file for this mod with relevant information and consider updating the Curse listing as well with some explanation of the recipes. In general, I expect that your mod is going to use vanilla-like recipes (6 blocks in a stair shape to produce stairs with that block's texture and (hopefully?) characteristics) but there's this whole complication in the form of the Stone Rod and Recipe Placeholder items that has no documentation whatsoever. I only figured them out thanks to JEI which is something most players will have but not all!

**Comment by SaymN** [comment]
I know about that.
If i've time i update the GitHub page :)
