### ISSUE TITLE
Suggestion - Unify Lamps and/or Add Lamp Conversion Recipes

### ISSUE THREAD

**Issue by jon-bartus** [SaymN/VanillaThings#13]
I don't really see myself using the lamps your mod adds personally as they're not my style, but one thing that I noticed while looking at them is that you've created the wall lamps as separate items from the normal floor/ceiling/table lamps.

The first option would be to get rid of the unnecessary second item, unifying them into a single item just like the Vanilla Torch and Lantern where their appearance changes depending upon how they're placed. Assuming that you had a reason for making them into separate items, my alternative suggestion would be that you add recipes for each lamp to be converted by placing it alone in the crafting grid. A similar recipe for converting horizontal slabs into vertical slabs would be useful as well.

**Comment by SaymN** [comment]
Fixed in 1.16.4-0.2
