### ISSUE TITLE
Suggestion - Restore Non-Stonecutter Recipes

### ISSUE THREAD

**Issue by jon-bartus** [SaymN/VanillaThings#14]
Minecraft has retained the default recipes for a reason. While I understand that #6 suggested adding the recipes to the Stonecutter, which is certainly a valid and valuable suggestion, removing the default crafting recipes makes what would be a very elegant mod that completely replicates Vanilla mechanics for blocks that Vanilla does not support into a confusing to use mess.

After your comment on #10, which was, frankly, a bit snide and rude, on my way to find the changelogs you felt that it was my duty to read in lieu of actual documentation, I happened across a number of comments on CurseForge which had been posted exhibiting the exact same confusion I experienced. The fact that you have had to give the answer to this question tells you that users are expecting the crafting to behave in this manner.

While I sympathize with #6 their niche needs with their specific combination of mods is currently dictating a change in behavior for this mod that is creating confusion for a large number of your users (relative to the **one** user who complained about a conflict). As the OP of #6 mentioned themselves, there are tools available for them to solve the issue in their specific use case without you having to abandon your original recipes which made perfect sense in the context of the default vanilla recipes everybody is familiar with. Further, implementation of #12 with the alternate recipes option would enable you to support all of the behavior people might be expecting.

**Comment by SaymN** [comment]
Fixed in 1.16.4-0.2
