### ISSUE TITLE
Slab Geometry Rendering Errors

### ISSUE THREAD

**Issue by jon-bartus** [SaymN/VanillaThings#15]
Hello, it's me again! I bet you probably hate seeing my name pop up by now.

This is a vertical slab.
![image](https://user-images.githubusercontent.com/9877274/77407633-d97e3f00-6d8c-11ea-82e1-01342b058b9f.png)

It plays nicely with horizontal slabs.
![image](https://user-images.githubusercontent.com/9877274/77407680-ebf87880-6d8c-11ea-87c0-6f773ecbbf26.png)

It plays nicely with adjacent vertical slabs that have the same orientation.
![image](https://user-images.githubusercontent.com/9877274/77407721-fb77c180-6d8c-11ea-8b05-f70286309609.png)

Unfortunately, if you place an adjacent vertical slab in the opposing orientation, things go a bit wrong.
![image](https://user-images.githubusercontent.com/9877274/77407793-14807280-6d8d-11ea-8a46-b035107ad464.png)

There's nothing wrong with the orientation, this vertical slab placed on top renders just fine.
![image](https://user-images.githubusercontent.com/9877274/77407961-62957600-6d8d-11ea-9aed-37f23d6e4de1.png)

The slab doesn't seem to care about an adjacent horizontal slab...
![image](https://user-images.githubusercontent.com/9877274/77408295-e2234500-6d8d-11ea-93f2-8261c10b4e60.png)

Placing this vertical slab next to the original one resolved the issue...
![image](https://user-images.githubusercontent.com/9877274/77407985-6a551a80-6d8d-11ea-8b50-e0f24a16a41a.png)

But wait, this is strange too! Now there's a corner shaped vertical slab where there's meant to be a flat one! It's also missing some of its geometry which shows the world behind it as though the block were invisible.
![image](https://user-images.githubusercontent.com/9877274/77408043-7b059080-6d8d-11ea-9ce0-6b126cb5de16.png)

(If the corner shaped slab is meant to be a way to create "vertical" stairs, I think that's awesome but you should really make it a separate item)

**Comment by SaymN** [comment]
Same as issue #16

**Comment by jon-bartus** [comment]
Hello, I agree that #16 and the last photo look at the same, but are you sure that the rest of the issue (slab appearing as a half-slab only taking up a quarter of the total block space) is the same?

**Comment by SaymN** [comment]
I know its a bit tricky, so i should exactly sho, where you place the slab and the orientation from your character.

**Comment by SaymN** [comment]
Fixed in 1.16.4-0.2
