### ISSUE TITLE
Stair Geometry Rendering Errors

### ISSUE THREAD

**Issue by jon-bartus** [SaymN/VanillaThings#16]
_Once more unto the breach, dear friend, once more!_

Yep, me again. This is somewhat related to #15 but I figured they might be similar but unrelated, so here you go!

Here's a staircase, placed on a wall for your viewing pleasure.
![image](https://user-images.githubusercontent.com/9877274/77408567-4d6d1700-6d8e-11ea-9a7c-977e406afcb6.png)

It renders just fine with an adjacent stair block of a different material in a different orientation.
![image](https://user-images.githubusercontent.com/9877274/77408623-6249aa80-6d8e-11ea-8b47-10feaeceeb47.png)
![image](https://user-images.githubusercontent.com/9877274/77408659-72618a00-6d8e-11ea-9d3d-db9c07debb5f.png)

Unfortunately, it doesn't play so nicely with its own material... (Hey, who put a village in my testing sandbox?! Darn villagers think they can live anywhere, I swear.)
![image](https://user-images.githubusercontent.com/9877274/77408684-79889800-6d8e-11ea-83b9-cd5e5f6e0ee7.png)
![image](https://user-images.githubusercontent.com/9877274/77408698-7e4d4c00-6d8e-11ea-8bee-af582f31d315.png)

I had hoped this was a quirk unique to the concrete, but alas...
![image](https://user-images.githubusercontent.com/9877274/77408830-b18fdb00-6d8e-11ea-8276-6cdadb15e6d1.png)

**Comment by SaymN** [comment]
Thx for this, i think it's s performance thing from mincraft itself. So just something to override ;)

**Comment by SaymN** [comment]
Fixed in Ver. 0.6
