### ISSUE TITLE
Some sides of blocks are transparent

### ISSUE THREAD

**Issue by traveldesign** [SaymN/VanillaThings#19]
Sometimes when I place down blocks I can see through all the way to the sky on one of the block's sides. If you'd like a screenshot I can get one for you.

**Comment by jon-bartus** [comment]
Is this on adjacent Stairs in different orientations, or slabs that are next to each other? If so, this is probably a duplicate of either #15 or #16 which have screenshots.

**Comment by traveldesign** [comment]
Yes, it's like #16. Except I could see all the way through the ground to the skybox below if that makes sense

**Comment by SaymN** [comment]
Fixed in Ver. 0.6
