### ISSUE TITLE
Add the Waterloggable state to blocks

### ISSUE THREAD

**Issue by WenXin20** [SaymN/VanillaThings#2]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Vanilla Things v0.4.6`

Adding the waterloggable state to non-full blocks could be good for decoration, especially the lamps.

**Comment by SaymN** [comment]
Thanks for your info, i will fix in next time :)

**Comment by WenXin20** [comment]
Thanks!

**Comment by SaymN** [comment]
Lamps and Tables can placed in water sources in the next update.
