### ISSUE TITLE
More Render Issues

### ISSUE THREAD

**Issue by WenXin20** [SaymN/VanillaThings#3]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Vanilla Things v0.4.6`

At certain angles, the corner vertical slabs will render incorrectly:
![2020-02-16_20 00 39](https://user-images.githubusercontent.com/12000593/74618549-f5405680-50f7-11ea-908a-89d14018c02f.png)

Glass slabs, vertical glass slabs, double glass slabs, and glass stairs (colored glasses too) all render inner seams instead of hiding them:
![2020-02-16_20 01 52](https://user-images.githubusercontent.com/12000593/74618589-1e60e700-50f8-11ea-8671-94dae9b04d0e.png)

Vertical Emerald, Coal, & Obsidian Slabs are also missing localization.

**Comment by SaymN** [comment]
Thanks for your info, i will fix in next time :)

**Comment by SaymN** [comment]
Localization fixed in the next update.

**Comment by WenXin20** [comment]
Just wanted to let you know that the lamps still have one more bug. When the Dark Oak Lamp placed on the ceiling, it is made of Dark Oak Planks, but when placed in the ground, it's made of regular oak planks. Same for the wall lanterns and other wood types.

**Comment by SaymN** [comment]
Ouh, thx for that. I will correct this.

**Comment by SaymN** [comment]
Is fixed in ver. 0.5.1
