### ISSUE TITLE
Add Item Tags to Stone Rods

### ISSUE THREAD

**Issue by WenXin20** [SaymN/VanillaThings#4]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Vanilla Things v0.4.6`

If Stone Rods are given the tag `#forge:rods` & `#forge:rods/stone`, they will be compatible with other mod's recipes that also use a stone rod, such as Silent Gear.

**Comment by SaymN** [comment]
Thanks for your info, i will fix in next time :)

**Comment by SaymN** [comment]
Tag and recipes will added/changed in the next update.
