### ISSUE TITLE
[1.15.2-0.4.2] Recipe override issue

### ISSUE THREAD

**Issue by kreezxil** [SaymN/VanillaThings#5]
https://github.com/kreezxil/foreshadowing/issues/16

Your're recipe to get stone bricks overrides the recipe the get chiseled stone blocks.

thankfully all of these special stone variants can be gotten from the stone cutter. Including yours. meaning your recipe might not be necessary either as soon as jei adds the feature to pull the recipes from the new vanilla machines.

https://github.com/mezz/JustEnoughItems/issues/1735

**Comment by SaymN** [comment]
yeah i think, i will remove the stoncutter recipes in the next update.

**Comment by SaymN** [comment]
For now i changed the recipe. Put 2 Ston Brick Slabs horizontal to get the Ston Bricks Block.
