### ISSUE TITLE
Wool Slabs

### ISSUE THREAD

**Issue by kreezxil** [SaymN/VanillaThings#6]
I guess you just implemented that before the weekend. We have comfort mod in our Foreshadowing 1.15.2 pack and it uses three wool blocks to make sleeping bags. But your wool slabs are now overriding it. I'll fix it on my end with crafttweaker.

Here's an idea, instead of  having all these conflicts have all of your recipes get moved over to the stonecutter. Granted they won't show up in JEI until JEI figures out how to read the stonecutter, but gone will be the conflicts with other mods.

**Comment by SaymN** [comment]
I will add an mod specific item, that can be used to bypass recipe conflicts.

**Comment by SaymN** [comment]
ver. 0.5.3 added a "Recipe placeholder" Item that not will consumed at crafting.
Use this for bypass Wool recipe conflicts.

**Comment by kreezxil** [comment]
is it active all the time? or do I have to set a configuration?

**Comment by SaymN** [comment]
It's always active. It's a second recipe.
Use JEI to show how to craft.

**Comment by kreezxil** [comment]
I was afraid of that, please knock out the original recipe as that one is the one that conflicts with comforts mod and still does. You didn't actually fix anything except provide a second recipe. I was hoping for you to provide a non-datapack/non-crafttweaker method, ie modify your mod. You did, but you didn't know out the original recipe. ;(

![Screenshot_20200223_130547](https://user-images.githubusercontent.com/3880072/75118180-8013da80-563d-11ea-9ef0-9bb70036a6a6.png)

**Comment by kreezxil** [comment]
for now i'll use crafttweaker to make the adjustments, thanks for your effort.

**Comment by SaymN** [comment]
Is fixed in ver. 0.5.5
The crafting recipe will adde in ver. 0.5.7.
