### ISSUE TITLE
Crafting recipes not working

### ISSUE THREAD

**Issue by potatokami** [SaymN/VanillaThings#8]
The recipes for Vertical slabs, slabs, walls, stairs and tables are not working. Other then that the mod is great! :)

**Comment by SaymN** [comment]
Minecraft and mod version?

**Comment by potatokami** [comment]
vanillathings-1.15.2-0.5.6.jar (The latest one)
 And minecraft 1.15.2

**Comment by SaymN** [comment]
Fix in Ver. 0.5.7 :)
